<?xml version="1.0" encoding="utf-8"?><Database Name="rbac" Class="rbacLINQ2SQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\rbac.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="pmt.Properties.Settings" SettingsPropertyName="rbacConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Action" Member="Action">
    <Type Name="Action">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Action_PermissionPerObject" Member="PermissionPerObject" ThisKey="Id" OtherKey="Action_Id" Type="PermissionPerObject" />
    </Type>
  </Table>
  <Table Name="dbo.ActiveRole" Member="ActiveRole">
    <Type Name="ActiveRole">
      <Column Name="Session_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_ActiveRole" Member="Role" ThisKey="Role_Id" OtherKey="Id" Type="Role" IsForeignKey="true" />
      <Association Name="Session_ActiveRole" Member="Session" ThisKey="Session_Id" OtherKey="Id" Type="Session" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AuthUserRole" Member="AuthUserRole">
    <Type Name="AuthUserRole">
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_AuthUserRole" Member="Role" ThisKey="Role_Id" OtherKey="Id" Type="Role" IsForeignKey="true" />
      <Association Name="User_AuthUserRole" Member="User" ThisKey="User_Id" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DynamicSOD" Member="DynamicSOD">
    <Type Name="DynamicSOD">
      <Column Name="Role_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ExclusiveRole_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_DynamicSOD" Member="Role" ThisKey="ExclusiveRole_Id" OtherKey="Id" Type="Role" IsForeignKey="true" />
      <Association Name="Role_DynamicSOD1" Member="Role1" ThisKey="Role_Id" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Object" Member="Object">
    <Type Name="Object">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Object_PermissionPerObject" Member="PermissionPerObject" ThisKey="Id" OtherKey="Object_Id" Type="PermissionPerObject" />
    </Type>
  </Table>
  <Table Name="dbo.Permission" Member="Permission">
    <Type Name="Permission">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Policy_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Permission_PermissionPerObject" Member="PermissionPerObject" ThisKey="Id" OtherKey="Permission_Id" Type="PermissionPerObject" />
      <Association Name="Permission_RolePermission" Member="RolePermission" ThisKey="Id" OtherKey="Permission_Id" Type="RolePermission" />
      <Association Name="Policy_Permission" Member="Policy" ThisKey="Policy_Id" OtherKey="Id" Type="Policy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PermissionPerObject" Member="PermissionPerObject">
    <Type Name="PermissionPerObject">
      <Column Name="Object_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Action_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Permission_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Action_PermissionPerObject" Member="Action" ThisKey="Action_Id" OtherKey="Id" Type="Action" IsForeignKey="true" />
      <Association Name="Object_PermissionPerObject" Member="Object" ThisKey="Object_Id" OtherKey="Id" Type="Object" IsForeignKey="true" />
      <Association Name="Permission_PermissionPerObject" Member="Permission" ThisKey="Permission_Id" OtherKey="Id" Type="Permission" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Policy" Member="Policy">
    <Type Name="Policy">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Policy_Permission" Member="Permission" ThisKey="Id" OtherKey="Policy_Id" Type="Permission" />
      <Association Name="Policy_Role" Member="Role" ThisKey="Id" OtherKey="Policy_Id" Type="Role" />
      <Association Name="Policy_User" Member="User" ThisKey="Id" OtherKey="Policy_Id" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Role">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Cardinality" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Policy_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Role_ActiveRole" Member="ActiveRole" ThisKey="Id" OtherKey="Role_Id" Type="ActiveRole" />
      <Association Name="Role_AuthUserRole" Member="AuthUserRole" ThisKey="Id" OtherKey="Role_Id" Type="AuthUserRole" />
      <Association Name="Role_DynamicSOD" Member="DynamicSOD" ThisKey="Id" OtherKey="ExclusiveRole_Id" Type="DynamicSOD" />
      <Association Name="Role_DynamicSOD1" Member="DynamicSOD1" ThisKey="Id" OtherKey="Role_Id" Type="DynamicSOD" />
      <Association Name="Role_RoleHierarchy" Member="RoleHierarchy" ThisKey="Id" OtherKey="ChildRole_Id" Type="RoleHierarchy" />
      <Association Name="Role_RoleHierarchy1" Member="RoleHierarchy1" ThisKey="Id" OtherKey="ParentRole_Id" Type="RoleHierarchy" />
      <Association Name="Role_RolePermission" Member="RolePermission" ThisKey="Id" OtherKey="Role_Id" Type="RolePermission" />
      <Association Name="Role_StaticSOD" Member="StaticSOD" ThisKey="Id" OtherKey="ExclusiveRole_Id" Type="StaticSOD" />
      <Association Name="Role_StaticSOD1" Member="StaticSOD1" ThisKey="Id" OtherKey="Role_Id" Type="StaticSOD" />
      <Association Name="Policy_Role" Member="Policy" ThisKey="Policy_Id" OtherKey="Id" Type="Policy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RoleHierarchy" Member="RoleHierarchy">
    <Type Name="RoleHierarchy">
      <Column Name="ParentRole_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChildRole_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_RoleHierarchy" Member="Role" ThisKey="ChildRole_Id" OtherKey="Id" Type="Role" IsForeignKey="true" />
      <Association Name="Role_RoleHierarchy1" Member="Role1" ThisKey="ParentRole_Id" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RolePermission" Member="RolePermission">
    <Type Name="RolePermission">
      <Column Name="Role_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Permission_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Permission_RolePermission" Member="Permission" ThisKey="Permission_Id" OtherKey="Id" Type="Permission" IsForeignKey="true" />
      <Association Name="Role_RolePermission" Member="Role" ThisKey="Role_Id" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Session" Member="Session">
    <Type Name="Session">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="Session_ActiveRole" Member="ActiveRole" ThisKey="Id" OtherKey="Session_Id" Type="ActiveRole" />
      <Association Name="User_Session" Member="User" ThisKey="User_Id" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StaticSOD" Member="StaticSOD">
    <Type Name="StaticSOD">
      <Column Name="Role_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ExclusiveRole_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_StaticSOD" Member="Role" ThisKey="ExclusiveRole_Id" OtherKey="Id" Type="Role" IsForeignKey="true" />
      <Association Name="Role_StaticSOD1" Member="Role1" ThisKey="Role_Id" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Policy_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_AuthUserRole" Member="AuthUserRole" ThisKey="Id" OtherKey="User_Id" Type="AuthUserRole" />
      <Association Name="User_Session" Member="Session" ThisKey="Id" OtherKey="User_Id" Type="Session" />
      <Association Name="Policy_User" Member="Policy" ThisKey="Policy_Id" OtherKey="Id" Type="Policy" IsForeignKey="true" />
    </Type>
  </Table>
</Database>